apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apigateway
  template:
    metadata:
      labels:
        app: apigateway
    spec:
      containers:
        - name: apigateway
          image: velikececi-e8ada5d7hzfhc0g9.azurecr.io/apigateway:prod
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          envFrom:
            - secretRef:
                name: app-secrets
            - secretRef:
                name: db-connections
            - configMapRef:
                name: app-config
          env:
            - name: ASPNETCORE_URLS
              value: http://+:5000
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 20
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: apigateway
spec:
  type: ClusterIP
  selector:
    app: apigateway
  ports:
    - name: http
      port: 80
      targetPort: 5000