apiVersion: apps/v1
kind: Deployment
metadata:
  name: identityservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identityservice
  template:
    metadata:
      labels:
        app: identityservice
    spec:
      containers:
        - name: identityservice
          image: velikececi-e8ada5d7hzfhc0g9.azurecr.io/identityservice:prod
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5001
          envFrom:
            - secretRef:
                name: app-secrets
            - secretRef:
                name: db-connections
            - configMapRef:
                name: app-config
          env:
            - name: ASPNETCORE_URLS
              value: http://+:5001
            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: db-connections
                  key: identity_ConnectionStrings__DefaultConnection
          readinessProbe:
            httpGet:
              path: /health
              port: 5001
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 5001
            initialDelaySeconds: 30
            periodSeconds: 20
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "400m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: identityservice
spec:
  type: ClusterIP
  selector:
    app: identityservice
  ports:
    - name: http
      port: 5001
      targetPort: 5001